packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    '@prisma/client': ^7.1.0
    prisma: latest

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - prisma

onlyBuiltDependencies:
  - esbuild
  - bcrypt
  - '@parcel/watcher'
